"""Add available_slots to destinations

Revision ID: 57ce89d80d3f
Revises: b30bee915faf
Create Date: 2025-05-21 01:51:52.828169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ce89d80d3f'
down_revision: Union[str, None] = 'b30bee915faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('available_slots', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'available_slots')
    # ### end Alembic commands ###
